# Generated by Django 4.0.3 on 2022-04-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(to='gram.comments'),
        ),
    ]
